language: node_js

services:
  - xvfb

addons:
  firefox: "latest"
  chrome: "stable"

node_js:
  - "10"

before_script:
  - 'export DISPLAY=:99.0'
  - 'sleep 3'
  - npm run-script symlink-plugin-to-ckeditor
  - npm install

env:
  - NPM_CMD=test

script:
  - "npm run-script $NPM_CMD"
